In [3]:
import pandas as pd

In [27]:
clean_df = pd.read_csv('coronavirus_states_raw.csv',index_col=False).drop(["#","Source","Projections"],axis=1)
clean_df

,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop,Population
0,USA Total,30365111,"+6,231",552556.0,86.0,22524111.0,7288444.0,91737.0,1669.0,385732183.0,1165345.0,NaN
1,California,3635598,NaN,56824.0,NaN,1914453.0,1664321.0,92012.0,1438.0,51601716.0,1305968.0,39512223.0
2,Texas,2749440,NaN,47257.0,NaN,2590824.0,111359.0,94822.0,1630.0,24507017.0,845190.0,28995881.0
3,Florida,1994117,NaN,32613.0,NaN,1329665.0,631839.0,92846.0,1518.0,24357867.0,1134098.0,21477737.0
4,New York,1811288,NaN,49539.0,NaN,932935.0,828814.0,93108.0,2547.0,42015555.0,2159787.0,19453561.0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,Navajo Nation,29987,NaN,1228.0,NaN,16289.0,12470.0,NaN,NaN,250472.0,NaN,NaN
61,Grand Princess Ship,122,NaN,7.0,NaN,115.0,0.0,NaN,NaN,NaN,NaN,NaN
62,Wuhan Repatriated,3,NaN,NaN,NaN,3.0,0.0,NaN,NaN,3.0,NaN,NaN
63,Diamond Princess Ship,46,NaN,NaN,NaN,46.0,0.0,NaN,NaN,46.0,NaN,NaN
64,Total:,30365111,"+6,231",552556.0,86.0,22524111.0,7288444.0,91737.0,1669.0,385732183.0,1165345.0,NaN

In [32]:
# Drop rows which are totals or non-state/territories e.g. Grand Princess Ship
clean_df.drop(clean_df[(clean_df["USAState"]=="Total:") | (clean_df["USAState"]=="USA Total") | (clean_df["USAState"]=="Federal Prisons") | (clean_df["USAState"]=="Navajo Nation") | (clean_df["USAState"]=="Grand Princess Ship")| (clean_df["USAState"]=="Wuhan Repatriated")| (clean_df["USAState"]=="Diamond Princess Ship")| (clean_df["USAState"]=="Veteran Affairs")| (clean_df["USAState"]=="US Military")].index, inplace=True)

,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop,Population
1,California,3635598,NaN,56824.0,NaN,1914453.0,1664321.0,92012.0,1438.0,51601716.0,1305968.0,39512223.0
2,Texas,2749440,NaN,47257.0,NaN,2590824.0,111359.0,94822.0,1630.0,24507017.0,845190.0,28995881.0
3,Florida,1994117,NaN,32613.0,NaN,1329665.0,631839.0,92846.0,1518.0,24357867.0,1134098.0,21477737.0
4,New York,1811288,NaN,49539.0,NaN,932935.0,828814.0,93108.0,2547.0,42015555.0,2159787.0,19453561.0
5,Illinois,1216090,NaN,23287.0,NaN,1135756.0,57047.0,95968.0,1838.0,19389098.0,1530096.0,12671821.0
6,Georgia,1040817,NaN,18420.0,NaN,596487.0,425910.0,98029.0,1735.0,8058303.0,758970.0,10617423.0
7,Ohio,995785,NaN,17992.0,NaN,946602.0,31191.0,85189.0,1539.0,10591209.0,906076.0,11689100.0
8,Pennsylvania,985066,"+2,944",24886.0,32.0,898699.0,61481.0,76946.0,1944.0,11158837.0,871649.0,12801989.0
9,North Carolina,891314,NaN,11783.0,NaN,852732.0,26799.0,84983.0,1123.0,10900126.0,1039287.0,10488084.0
10,New Jersey,853349,NaN,24076.0,NaN,627532.0,201741.0,96074.0,2711.0,11474078.0,1291807.0,8882190.0
11,Arizona,834607,NaN,16645.0,NaN,785612.0,32350.0,114664.0,2287.0,4401682.0,604733.0,7278717.0
12,Tennessee,796624,NaN,11681.0,NaN,772665.0,12278.0,116650.0,1710.0,7034682.0,1030093.0,6829174.0
13,Michigan,683398,NaN,16843.0,NaN,556697.0,109858.0,68430.0,1687.0,11570859.0,1158609.0,9986857.0
14,Indiana,675388,NaN,12907.0,NaN,520198.0,142283.0,100322.0,1917.0,8556561.0,1270987.0,6732219.0
15,Massachusetts,608318,NaN,16759.0,NaN,565929.0,25630.0,88258.0,2431.0,17714455.0,2570105.0,6892503.0
16,Virginia,600550,NaN,10182.0,NaN,49395.0,540973.0,70359.0,1193.0,8043259.0,942328.0,8535519.0
17,Wisconsin,571220,NaN,6556.0,NaN,558115.0,6549.0,98107.0,1126.0,3249111.0,558033.0,5822434.0
18,Missouri,568926,NaN,8914.0,NaN,386465.0,173547.0,92698.0,1452.0,5866988.0,955936.0,6137428.0
19,South Carolina,537498,NaN,8938.0,NaN,NaN,NaN,104395.0,1736.0,6433793.0,1249592.0,5148714.0
20,Alabama,510048,NaN,10391.0,NaN,310742.0,188915.0,104024.0,2119.0,2492531.0,508349.0,4903185.0
21,Minnesota,501458,NaN,6830.0,NaN,485358.0,9270.0,88917.0,1211.0,7847879.0,1391559.0,5639632.0
22,Colorado,446580,NaN,6142.0,NaN,299195.0,141243.0,77548.0,1067.0,2662341.0,462313.0,5758736.0
23,Louisiana,439543,NaN,9974.0,NaN,426243.0,3326.0,94550.0,2146.0,6311156.0,1357590.0,4648794.0
24,Oklahoma,434075,NaN,4788.0,NaN,417734.0,11553.0,109699.0,1210.0,3671576.0,927875.0,3956971.0
25,Kentucky,419149,NaN,5504.0,NaN,48964.0,364681.0,93818.0,1232.0,4739044.0,1060741.0,4467673.0
26,Maryland,397898,"+1,152",8132.0,19.0,9797.0,379969.0,65815.0,1345.0,8433019.0,1394883.0,6045680.0
27,Utah,380340,NaN,2041.0,NaN,367018.0,11281.0,118635.0,637.0,4066552.0,1268436.0,3205958.0
28,Iowa,372868,+428,5672.0,NaN,326506.0,40690.0,118181.0,1798.0,4303965.0,1364142.0,3155070.0
29,Washington,356063,NaN,5230.0,NaN,176006.0,174827.0,46759.0,687.0,5630802.0,739446.0,7614893.0
30,Arkansas,328045,NaN,5515.0,NaN,319771.0,2759.0,108703.0,1827.0,3299489.0,1093341.0,3017804.0
31,Mississippi,301924,NaN,6938.0,NaN,287341.0,7645.0,101448.0,2331.0,2560505.0,860342.0,2976149.0
32,Kansas,301763,NaN,4850.0,NaN,282625.0,14288.0,103581.0,1665.0,1293893.0,444131.0,2913314.0
33,Nevada,300415,NaN,5157.0,NaN,269236.0,26022.0,97532.0,1674.0,2863567.0,929682.0,3080156.0
34,Connecticut,295484,NaN,7822.0,NaN,259572.0,28090.0,82878.0,2194.0,7274861.0,2040470.0,3565287.0
35,Nebraska,205539,NaN,2130.0,NaN,158999.0,44410.0,106254.0,1101.0,986473.0,509961.0,1934408.0
36,New Mexico,189158,NaN,3877.0,NaN,169889.0,15392.0,90211.0,1849.0,2885907.0,1376320.0,2096829.0
37,Idaho,176802,NaN,1938.0,NaN,98510.0,76354.0,98934.0,1084.0,1148603.0,642732.0,1787065.0
38,Oregon,160622,NaN,2353.0,NaN,141121.0,17148.0,38083.0,558.0,4021248.0,953414.0,4217737.0
39,West Virginia,137092,+376,2600.0,30.0,129143.0,5349.0,76496.0,1451.0,2341373.0,1306463.0,1792147.0
40,Rhode Island,132616,NaN,2594.0,NaN,8124.0,121898.0,125185.0,2449.0,3301005.0,3116034.0,1059361.0
41,South Dakota,115203,NaN,1919.0,NaN,111120.0,2164.0,130223.0,2169.0,435353.0,492114.0,884659.0
42,Montana,102616,NaN,1406.0,NaN,100217.0,993.0,96012.0,1316.0,1151030.0,1076959.0,1068778.0
43,North Dakota,101403,NaN,1459.0,NaN,99171.0,773.0,133064.0,1915.0,410293.0,538398.0,762062.0
44,Delaware,91425,NaN,1517.0,NaN,83108.0,6800.0,93888.0,1558.0,647072.0,664506.0,973764.0
45,New Hampshire,79702,NaN,1207.0,NaN,76155.0,2340.0,58617.0,888.0,1794066.0,1319447.0,1359711.0
46,Alaska,58580,NaN,306.0,NaN,50446.0,7828.0,80077.0,418.0,1820986.0,2489233.0,731545.0
47,Wyoming,55479,NaN,693.0,NaN,54378.0,408.0,95859.0,1197.0,668703.0,1155408.0,578759.0
48,Maine,48070,+238,728.0,1.0,12909.0,34433.0,35761.0,542.0,1996240.0,1485063.0,1344212.0
49,District Of Columbia,42892,NaN,1046.0,NaN,30631.0,11215.0,60775.0,1482.0,1314784.0,1862963.0,705749.0
50,Hawaii,28509,NaN,451.0,NaN,NaN,NaN,20135.0,319.0,1199823.0,847409.0,1415872.0
51,Vermont,17247,NaN,217.0,NaN,14507.0,2523.0,27640.0,348.0,1214526.0,1946390.0,623989.0
52,Puerto Rico,194704,"+1,093",2089.0,4.0,93486.0,99129.0,57487.0,617.0,464073.0,137018.0,3386941.0
53,Guam,7780,NaN,134.0,NaN,7618.0,28.0,NaN,NaN,136135.0,NaN,NaN
54,United States Virgin Islands,2804,NaN,25.0,NaN,NaN,NaN,NaN,NaN,50108.0,NaN,NaN
55,Northern Mariana Islands,157,NaN,2.0,NaN,NaN,NaN,NaN,NaN,26131.0,NaN,NaN
56,American Samoa,3,NaN,NaN,NaN,3.0,0.0,NaN,NaN,NaN,NaN,NaN

In [34]:
# Drop columns which could be calculated in the database
cols=[7,8,10]
clean_df.drop(clean_df.columns[cols],axis=1,inplace=True)

In [64]:
# Convert all data types to integers/floats by removing commas, special characters etc. 
clean_new_cases = pd.concat([clean_df["NewCases"].str.split()
                               .str[0]
                               .str.replace(',','').astype(float) for col in clean_df], axis=1)

In [65]:
# replace the old columns with the new
clean_df["NewCases"] = clean_new_cases

In [67]:
# check the types
clean_df.dtypes

USAState           object
TotalCases          int64
NewCases          float64
TotalDeaths       float64
NewDeaths         float64
TotalRecovered    float64
ActiveCases       float64
TotalTests        float64
Population        float64
dtype: object

In [69]:
# reset the index
clean_df.set_index("USAState")

,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,TotalTests,Population
USAState,,,,,,,,
California,3635598,NaN,56824.0,NaN,1914453.0,1664321.0,51601716.0,39512223.0
Texas,2749440,NaN,47257.0,NaN,2590824.0,111359.0,24507017.0,28995881.0
Florida,1994117,NaN,32613.0,NaN,1329665.0,631839.0,24357867.0,21477737.0
New York,1811288,NaN,49539.0,NaN,932935.0,828814.0,42015555.0,19453561.0
Illinois,1216090,NaN,23287.0,NaN,1135756.0,57047.0,19389098.0,12671821.0
Georgia,1040817,NaN,18420.0,NaN,596487.0,425910.0,8058303.0,10617423.0
Ohio,995785,NaN,17992.0,NaN,946602.0,31191.0,10591209.0,11689100.0
Pennsylvania,985066,2944.0,24886.0,32.0,898699.0,61481.0,11158837.0,12801989.0
North Carolina,891314,NaN,11783.0,NaN,852732.0,26799.0,10900126.0,10488084.0
New Jersey,853349,NaN,24076.0,NaN,627532.0,201741.0,11474078.0,8882190.0
Arizona,834607,NaN,16645.0,NaN,785612.0,32350.0,4401682.0,7278717.0
Tennessee,796624,NaN,11681.0,NaN,772665.0,12278.0,7034682.0,6829174.0
Michigan,683398,NaN,16843.0,NaN,556697.0,109858.0,11570859.0,9986857.0
Indiana,675388,NaN,12907.0,NaN,520198.0,142283.0,8556561.0,6732219.0
Massachusetts,608318,NaN,16759.0,NaN,565929.0,25630.0,17714455.0,6892503.0
Virginia,600550,NaN,10182.0,NaN,49395.0,540973.0,8043259.0,8535519.0
Wisconsin,571220,NaN,6556.0,NaN,558115.0,6549.0,3249111.0,5822434.0
Missouri,568926,NaN,8914.0,NaN,386465.0,173547.0,5866988.0,6137428.0
South Carolina,537498,NaN,8938.0,NaN,NaN,NaN,6433793.0,5148714.0
Alabama,510048,NaN,10391.0,NaN,310742.0,188915.0,2492531.0,4903185.0
Minnesota,501458,NaN,6830.0,NaN,485358.0,9270.0,7847879.0,5639632.0
Colorado,446580,NaN,6142.0,NaN,299195.0,141243.0,2662341.0,5758736.0
Louisiana,439543,NaN,9974.0,NaN,426243.0,3326.0,6311156.0,4648794.0
Oklahoma,434075,NaN,4788.0,NaN,417734.0,11553.0,3671576.0,3956971.0
Kentucky,419149,NaN,5504.0,NaN,48964.0,364681.0,4739044.0,4467673.0
Maryland,397898,1152.0,8132.0,19.0,9797.0,379969.0,8433019.0,6045680.0
Utah,380340,NaN,2041.0,NaN,367018.0,11281.0,4066552.0,3205958.0
Iowa,372868,428.0,5672.0,NaN,326506.0,40690.0,4303965.0,3155070.0
Washington,356063,NaN,5230.0,NaN,176006.0,174827.0,5630802.0,7614893.0
Arkansas,328045,NaN,5515.0,NaN,319771.0,2759.0,3299489.0,3017804.0
Mississippi,301924,NaN,6938.0,NaN,287341.0,7645.0,2560505.0,2976149.0
Kansas,301763,NaN,4850.0,NaN,282625.0,14288.0,1293893.0,2913314.0
Nevada,300415,NaN,5157.0,NaN,269236.0,26022.0,2863567.0,3080156.0
Connecticut,295484,NaN,7822.0,NaN,259572.0,28090.0,7274861.0,3565287.0
Nebraska,205539,NaN,2130.0,NaN,158999.0,44410.0,986473.0,1934408.0
New Mexico,189158,NaN,3877.0,NaN,169889.0,15392.0,2885907.0,2096829.0
Idaho,176802,NaN,1938.0,NaN,98510.0,76354.0,1148603.0,1787065.0
Oregon,160622,NaN,2353.0,NaN,141121.0,17148.0,4021248.0,4217737.0
West Virginia,137092,376.0,2600.0,30.0,129143.0,5349.0,2341373.0,1792147.0
Rhode Island,132616,NaN,2594.0,NaN,8124.0,121898.0,3301005.0,1059361.0
South Dakota,115203,NaN,1919.0,NaN,111120.0,2164.0,435353.0,884659.0
Montana,102616,NaN,1406.0,NaN,100217.0,993.0,1151030.0,1068778.0
North Dakota,101403,NaN,1459.0,NaN,99171.0,773.0,410293.0,762062.0
Delaware,91425,NaN,1517.0,NaN,83108.0,6800.0,647072.0,973764.0
New Hampshire,79702,NaN,1207.0,NaN,76155.0,2340.0,1794066.0,1359711.0
Alaska,58580,NaN,306.0,NaN,50446.0,7828.0,1820986.0,731545.0
Wyoming,55479,NaN,693.0,NaN,54378.0,408.0,668703.0,578759.0
Maine,48070,238.0,728.0,1.0,12909.0,34433.0,1996240.0,1344212.0
District Of Columbia,42892,NaN,1046.0,NaN,30631.0,11215.0,1314784.0,705749.0
Hawaii,28509,NaN,451.0,NaN,NaN,NaN,1199823.0,1415872.0
Vermont,17247,NaN,217.0,NaN,14507.0,2523.0,1214526.0,623989.0
Puerto Rico,194704,1093.0,2089.0,4.0,93486.0,99129.0,464073.0,3386941.0
Guam,7780,NaN,134.0,NaN,7618.0,28.0,136135.0,NaN
United States Virgin Islands,2804,NaN,25.0,NaN,NaN,NaN,50108.0,NaN
Northern Mariana Islands,157,NaN,2.0,NaN,NaN,NaN,26131.0,NaN
American Samoa,3,NaN,NaN,NaN,3.0,0.0,NaN,NaN

In [70]:
# Export the clean data to a csv
clean_df.to_csv('coronavirus_states_clean.csv',index=False)